HEAT-227: updated pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -42,40 +42,40 @@ jobs:
         with:
           environment: ${{ inputs.environment }}   
 
-      - name: Set Kubernetes Namespace secrets
-        id: set_namespace_secrets
-        run: |
-          if [[ "${{ inputs.environment }}" == "development" ]]; then
-            api=https://"{{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
-            cert="${{ secrets.DEVELOPMENT_KUBE_CERT }}"
-            cluster="${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
-            namespace="${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}"
-            token="${{ secrets.DEVELOPMENT_KUBE_TOKEN }}"
-            bash ./.github/actions/cloud-platform-deploy
-          elif [[ "${{ inputs.environment }}" == "production" ]]; then
-            api=https://"{{ secrets.PRODUCTION_KUBE_CLUSTER }}"
-            cert="${{ secrets.PRODUCTION_KUBE_CERT }}"
-            cluster="${{ secrets.PRODUCTION_KUBE_CLUSTER }}"
-            namespace="${{ secrets.PRODUCTION_KUBE_NAMESPACE }}"
-            token="${{ secrets.PRODUCTION_KUBE_TOKEN }}"
-          else
-            echo "Invalid Github environment/namespace specified: ${{ inputs.environment }}"
-            exit 1
-          fi
-      - uses: ./.github/actions/cloud-platform-deploy
+      # - name: Set Kubernetes Namespace secrets
+      #   id: set_namespace_secrets
+      #   run: |
+      #     if [[ "${{ inputs.environment }}" == "development" ]]; then
+      #       api=https://"{{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
+      #       cert="${{ secrets.DEVELOPMENT_KUBE_CERT }}"
+      #       cluster="${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
+      #       namespace="${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}"
+      #       token="${{ secrets.DEVELOPMENT_KUBE_TOKEN }}"
+      #       bash ./.github/actions/cloud-platform-deploy
+      #     elif [[ "${{ inputs.environment }}" == "production" ]]; then
+      #       api=https://"{{ secrets.PRODUCTION_KUBE_CLUSTER }}"
+      #       cert="${{ secrets.PRODUCTION_KUBE_CERT }}"
+      #       cluster="${{ secrets.PRODUCTION_KUBE_CLUSTER }}"
+      #       namespace="${{ secrets.PRODUCTION_KUBE_NAMESPACE }}"
+      #       token="${{ secrets.PRODUCTION_KUBE_TOKEN }}"
+      #     else
+      #       echo "Invalid Github environment/namespace specified: ${{ inputs.environment }}"
+      #       exit 1
+      #     fi
 
 
-      # - name: Deploy to Platform
-      # #  if: ${{ steps.check_files.outputs.files_exists == 'true' && steps.enabled.outputs.enabled == 'true' }}  
-      #   uses: ./.github/actions/cloud-platform-deploy
-      #   with:
-      #     environment: ${{ inputs.environment }}
-      #     version: ${{ inputs.version }}
-      #     api: https://${{ secrets.KUBE_CLUSTER }}
-      #     cert: ${{ secrets.KUBE_CERT }}
-      #     cluster: ${{ secrets.KUBE_CLUSTER }}
-      #     namespace: ${{ secrets.KUBE_NAMESPACE }}
-      #     token: ${{ secrets.KUBE_TOKEN }}
+
+      - name: Deploy to Platform
+      #  if: ${{ steps.check_files.outputs.files_exists == 'true' && steps.enabled.outputs.enabled == 'true' }}  
+        uses: ./.github/actions/cloud-platform-deploy
+        with:
+          environment: ${{ inputs.environment }}
+          version: ${{ inputs.version }}
+          api: https://${{ secrets.KUBE_CLUSTER }}
+          cert: ${{ secrets.KUBE_CERT }}
+          cluster: ${{ secrets.KUBE_CLUSTER }}
+          namespace: ${{ secrets.KUBE_NAMESPACE }}
+          token: ${{ secrets.KUBE_TOKEN }}
 
       # - name: Deploy to Prod
       # # if: ${{ steps.check_files.outputs.files_exists == 'true' && steps.enabled.outputs.enabled == 'true' }}  
