HEAT-227: updated pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,11 +36,32 @@ jobs:
       name: ${{ inputs.environment }}  
     steps:
       - uses: actions/checkout@v4
+      - uses: ./.github/actions/cloud-platform-deploy
       - uses: ./.github/actions/get-env-details
         id: env
         with:
-          environment: ${{ inputs.environment }}
+          environment: ${{ inputs.environment }}   
 
+      - name: Set Kubernetes Namespace secrets
+        id: set_namespace_secrets
+        run: |
+          if [[ "${{ inputs.environment }}" == "development" ]]; then
+            api=https://"{{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
+            cert="${{ secrets.DEVELOPMENT_KUBE_CERT }}"
+            cluster="${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
+            namespace="${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}"
+            token="${{ secrets.DEVELOPMENT_KUBE_TOKEN }}"
+          elif [[ "${{ inputs.environment }}" == "production" ]]; then
+            api=https://"{{ secrets.PRODUCTION_KUBE_CLUSTER }}"
+            cert="${{ secrets.PRODUCTION_KUBE_CERT }}"
+            cluster="${{ secrets.PRODUCTION_KUBE_CLUSTER }}"
+            namespace="${{ secrets.PRODUCTION_KUBE_NAMESPACE }}"
+            token="${{ secrets.PRODUCTION_KUBE_TOKEN }}"
+          else
+            echo "Invalid Github environment/namespace specified: ${{ inputs.environment }}"
+            exit 1
+          fi
+        
       # - name: Deploy to Platform
       # #  if: ${{ steps.check_files.outputs.files_exists == 'true' && steps.enabled.outputs.enabled == 'true' }}  
       #   uses: ./.github/actions/cloud-platform-deploy
@@ -64,8 +85,6 @@ jobs:
       #     cluster: ${{ secrets.PRODUCTION_KUBE_CLUSTER }}
       #     namespace: ${{ secrets.PRODUCTION_KUBE_NAMESPACE }}
       #     token: ${{ secrets.PRODUCTION_KUBE_TOKEN }}
-
-        
 # jobs:
 #   deploy:
 #     runs-on: ubuntu-latest
@@ -97,24 +116,3 @@ jobs:
 #         namespace: ${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}
 #         token: ${{ secrets.DEVELOPMENT_KUBE_TOKEN }}    
 
-
-      - name: Set Kubernetes Namespace secrets
-        id: set_namespace_secrets
-        run: |
-          if [[ "${{ inputs.environment }}" == "development" ]]; then
-            api=https://"{{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
-            cert="${{ secrets.DEVELOPMENT_KUBE_CERT }}"
-            cluster="${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
-            namespace="${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}"
-            token="${{ secrets.DEVELOPMENT_KUBE_TOKEN }}"
-          elif [[ "${{ inputs.environment }}" == "production" ]]; then
-            api=https://"{{ secrets.PRODUCTION_KUBE_CLUSTER }}"
-            cert="${{ secrets.PRODUCTION_KUBE_CERT }}"
-            cluster="${{ secrets.PRODUCTION_KUBE_CLUSTER }}"
-            namespace="${{ secrets.PRODUCTION_KUBE_NAMESPACE }}"
-            token="${{ secrets.PRODUCTION_KUBE_TOKEN }}"
-          else
-            echo "Invalid Github environment/namespace specified: ${{ inputs.environment }}"
-            exit 1
-          fi
-          uses: ./.github/actions/cloud-platform-deploy
