HEAT-227: Updated ipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,26 +51,47 @@ jobs:
       - name: Set Kubernetes Namespace secrets
         id: set_namespace_secrets
         run: |
-          case "${{ inputs.github_environment }}" in 
-          ("development")
+          if [[ "${{ inputs.github_environment }}" == "development" ]]; then
             api=https://"{{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
             cert="${{ secrets.DEVELOPMENT_KUBE_CERT }}"
             cluster="${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
             namespace="${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}"
             token="${{ secrets.DEVELOPMENT_KUBE_TOKEN }}"
-            ;;
-          ("production")
+          elif [[ "${{ inputs.github_environment }}" == "production" ]]; then
             api=https://"{{ secrets.PRODUCTION_KUBE_CLUSTER }}"
             cert="${{ secrets.PRODUCTION_KUBE_CERT }}"
             cluster="${{ secrets.PRODUCTION_KUBE_CLUSTER }}"
             namespace="${{ secrets.PRODUCTION_KUBE_NAMESPACE }}"
             token="${{ secrets.PRODUCTION_KUBE_TOKEN }}"
-            ;;
-          (*)
+          else
             echo "Invalid Github environment/namespace specified: ${{ inputs.github_environment }}"
             exit 1
-            ;;
-          esac
+          fi
+
+
+
+
+
+          # case "${{ inputs.github_environment }}" in 
+          # ("development")
+          #   api=https://"{{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
+          #   cert="${{ secrets.DEVELOPMENT_KUBE_CERT }}"
+          #   cluster="${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
+          #   namespace="${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}"
+          #   token="${{ secrets.DEVELOPMENT_KUBE_TOKEN }}"
+          #   ;;
+          # ("production")
+          #   api=https://"{{ secrets.PRODUCTION_KUBE_CLUSTER }}"
+          #   cert="${{ secrets.PRODUCTION_KUBE_CERT }}"
+          #   cluster="${{ secrets.PRODUCTION_KUBE_CLUSTER }}"
+          #   namespace="${{ secrets.PRODUCTION_KUBE_NAMESPACE }}"
+          #   token="${{ secrets.PRODUCTION_KUBE_TOKEN }}"
+          #   ;;
+          # (*)
+          #   echo "Invalid Github environment/namespace specified: ${{ inputs.github_environment }}"
+          #   exit 1
+          #   ;;
+          # esac
 
 
         
