HEAT-227: Updated ipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,7 +47,7 @@ jobs:
       name: ${{ inputs.github_environment }}  
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
       # - name: Env details
       #   uses: ./.github/actions/get-env-details
       #   id: env
@@ -74,64 +74,49 @@ jobs:
       #       exit 1
       #     fi
 
-      - name: Deploy to Cloud Platform
-        # if: ${{ steps.check_files.outputs.files_exists == 'true' && steps.enabled.outputs.enabled == 'true' }}
+      - name: Deploy to Dev
+      # if: ${{ steps.check_files.outputs.files_exists == 'true' && steps.enabled.outputs.enabled == 'true' }}  
         uses: ./.github/actions/cloud-platform-deploy
         with:
-          project: ${{ matrix.project }}
           environment: ${{ inputs.environment }}
           version: ${{ inputs.version }}
-          api: ${{ secrets.KUBE_ENV_API }}
-          cert: ${{ secrets.KUBE_CERT }}
-          cluster: ${{ secrets.KUBE_CLUSTER }}
-          namespace: ${{ secrets.KUBE_NAMESPACE }}
-          token: ${{ secrets.KUBE_TOKEN }}
-          github_token: ${{ secrets.BOT_GITHUB_EXTERNAL_REPOS_TOKEN }}
+          api: https://${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}
+          cert: ${{ secrets.DEVELOPMENT_KUBE_CERT }}
+          cluster: ${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}
+          namespace: ${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}
+          token: ${{ secrets.DEVELOPMENT_KUBE_TOKEN }}
 
+      - name: Set Kubernetes Namespace secrets
+        id: set_namespace_secrets
+        run: |
+          if [[ "${{ inputs.github_environment }}" == "development" ]]; then
+            api=https://"{{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
+            cert="${{ secrets.DEVELOPMENT_KUBE_CERT }}"
+            cluster="${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
+            namespace="${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}"
+            token="${{ secrets.DEVELOPMENT_KUBE_TOKEN }}"
+          elif [[ "${{ inputs.github_environment }}" == "production" ]]; then
+            api=https://"{{ secrets.PRODUCTION_KUBE_CLUSTER }}"
+            cert="${{ secrets.PRODUCTION_KUBE_CERT }}"
+            cluster="${{ secrets.PRODUCTION_KUBE_CLUSTER }}"
+            namespace="${{ secrets.PRODUCTION_KUBE_NAMESPACE }}"
+            token="${{ secrets.PRODUCTION_KUBE_TOKEN }}"
+          else
+            echo "Invalid Github environment/namespace specified: ${{ inputs.github_environment }}"
+            exit 1
+          fi
 
-      # - name: Deploy to Dev
-      # # if: ${{ steps.check_files.outputs.files_exists == 'true' && steps.enabled.outputs.enabled == 'true' }}  
-      #   uses: ./.github/actions/cloud-platform-deploy
-      #   with:
-      #     environment: ${{ inputs.environment }}
-      #     version: ${{ inputs.version }}
-      #     api: https://${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}
-      #     cert: ${{ secrets.DEVELOPMENT_KUBE_CERT }}
-      #     cluster: ${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}
-      #     namespace: ${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}
-      #     token: ${{ secrets.DEVELOPMENT_KUBE_TOKEN }}
-
-      # - name: Set Kubernetes Namespace secrets
-      #   id: set_namespace_secrets
-      #   run: |
-      #     if [[ "${{ inputs.github_environment }}" == "development" ]]; then
-      #       api=https://"{{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
-      #       cert="${{ secrets.DEVELOPMENT_KUBE_CERT }}"
-      #       cluster="${{ secrets.DEVELOPMENT_KUBE_CLUSTER }}"
-      #       namespace="${{ secrets.DEVELOPMENT_KUBE_NAMESPACE }}"
-      #       token="${{ secrets.DEVELOPMENT_KUBE_TOKEN }}"
-      #     elif [[ "${{ inputs.github_environment }}" == "production" ]]; then
-      #       api=https://"{{ secrets.PRODUCTION_KUBE_CLUSTER }}"
-      #       cert="${{ secrets.PRODUCTION_KUBE_CERT }}"
-      #       cluster="${{ secrets.PRODUCTION_KUBE_CLUSTER }}"
-      #       namespace="${{ secrets.PRODUCTION_KUBE_NAMESPACE }}"
-      #       token="${{ secrets.PRODUCTION_KUBE_TOKEN }}"
-      #     else
-      #       echo "Invalid Github environment/namespace specified: ${{ inputs.github_environment }}"
-      #       exit 1
-      #     fi
-
-      # - name: Deploy to Prod
-      # # if: ${{ steps.check_files.outputs.files_exists == 'true' && steps.enabled.outputs.enabled == 'true' }}  
-      #   uses: ./.github/actions/cloud-platform-deploy
-      #   with:
-      #     environment: ${{ inputs.github_environment }}
-      #     version: ${{ inputs.version }}
-      #     api: https://${{ secrets.PRODUCTION_KUBE_CLUSTER }}
-      #     cert: ${{ secrets.PRODUCTION_KUBE_CERT }}
-      #     cluster: ${{ secrets.PRODUCTION_KUBE_CLUSTER }}
-      #     namespace: ${{ secrets.PRODUCTION_KUBE_NAMESPACE }}
-      #     token: ${{ secrets.PRODUCTION_KUBE_TOKEN }}
+      - name: Deploy to Prod
+      # if: ${{ steps.check_files.outputs.files_exists == 'true' && steps.enabled.outputs.enabled == 'true' }}  
+        uses: ./.github/actions/cloud-platform-deploy
+        with:
+          environment: ${{ inputs.github_environment }}
+          version: ${{ inputs.version }}
+          api: https://${{ secrets.PRODUCTION_KUBE_CLUSTER }}
+          cert: ${{ secrets.PRODUCTION_KUBE_CERT }}
+          cluster: ${{ secrets.PRODUCTION_KUBE_CLUSTER }}
+          namespace: ${{ secrets.PRODUCTION_KUBE_NAMESPACE }}
+          token: ${{ secrets.PRODUCTION_KUBE_TOKEN }}
 
         
 # jobs:
